spring:
  application:
    name: order-projector

  data:
    mongodb:
      host: localhost
      database: order

messaging:
  kafka:
    bootstrapServers: localhost:9092
    topic: order.events
    groupId: order-projector-consumer

server:
  port: 8080
